'''
Core loop:
    1. draft model samples K tokens at a time from M_q(x|P) where P is prefix. 
            sampling results in tokens x1, .., x_K. 
    2. target model runs one forward pass on M_p(P, x_1, ..., x_K)
        (i.e. runs on input of the prefix plus all K tokens generated by the 
        draft model)
    3. Rejection sampling. 
        The probability that you accept the token x_i from the draft model is 
        min(1, p_i(v_i) / q_i(v_i)). do rejection sampling with this probability of accepting. 
    4. If you accept all the tokens the draft model proposed, then sample the next one from M_p. 
    Otherwise, sample the corrected token from the norm adjusted difference distribution
        p_i_new = (max(0, p_i(x) - q_i(x)) / sum_z (max(0, p_i(z) - q_i(z)))

Why does this work: 
Case #1: p(x) <= q(x). 
    Then the probability of getting token x through out method is q(x) * min(1, p(x)/q(x)) = p(x)
    So this is equivalent to sampling from the target model
Case #2: p(x) > q(x)
    Then the probability of getting token x through this method is q(x) * 1 = q(x). 
    This is corrected for in the correction step. 

When you reject x_i, you can't just sample from p directly. This is because by rejecting, you've 
conditioned on the event "x_i was not accepted". Sampling from p would throw out that
information. 

The corrected distribution max(0, p(x) - q(x)) is what is left of p after you remove the part
"covered" by the accepted portion of q. 
    * When p(x) > q(x), the draft underrepresented this token, so there's leftover mass 
    that wasn't accounted for by the accepted drafts. 
    * When p(x) <= q(x), the draft already covered this token via acceptance step, so no residual. 

We normalize this residual to get a valid distribution to sample from. 

TODO next: look at K vs acceptance rate
'''

import argparse
import time
import torch
import torch.nn.functional as F
from transformers import AutoModelForCausalLM, AutoTokenizer

def load_models(draft_name: str, target_name: str, device: str):
    print("Loading draft model: ", draft_name)
    tokenizer = AutoTokenizer.from_pretrained(draft_name)
    draft = AutoModelForCausalLM.from_pretrained(draft_name, torch_dtype=torch.float32).to(device).eval()

    print("Loading target model: ", target_name)
    target = AutoModelForCausalLM.from_pretrained(target_name, torch_dtype=torch.float32).to(device).eval()

    return tokenizer, draft, target

def forward_pass(model, temperature, input_ids: torch.Tensor) -> torch.Tensor:
    """
    Single model forward pass to get p(x)
    """

    with torch.no_grad():
        logits = model(input_ids).logits[0]
        # output is shape [seq_len, vocab_size]
    if temperature == 0:
        probs = torch.zeros_like(logits)
        probs.scatter_(1, logits.argmax(dim=-1, keepdim=True), 1.0)
        return probs
    return F.softmax(logits / temperature, dim=-1)


def speculative_decode(
    draft_model, target_model, tokenizer,
    input_ids: torch.Tensor, # [1, seq_len]
    K: int, # number of draft tokens to propose
    max_new_tokens: int, 
    temperature: float = 1.0, 
    device: str = "cpu"
) -> torch.Tensor:
    full_seq = input_ids.clone()
    round_num=0
    # while we haven't hit the max number of tokens or EOS token, keep generating
    while full_seq.shape[1] - input_ids.shape[1] < max_new_tokens:

        print(f"prefix: {tokenizer.decode(full_seq[0], skip_special_tokens=True)}")

        # input to draft model
        draft_model_input = full_seq.clone()

        # save the q_i(v_i) also
        q_i_v_i = []
        # draft tokens
        draft_tokens = []
        q_probs_full = []

        for i in range(K):
             # draft model to sample K tokens
            q_probs = forward_pass(draft_model, temperature, draft_model_input) # [seq_len, vocab_size]
            q_probs_full.append(q_probs[-1, :])
            # sample from the last position in q_probs to get the next proposed token from the draft model.
            draft_token = torch.multinomial(q_probs[-1, :], 1)
            q_i_v_i.append(q_probs[-1, draft_token.item()])
            draft_tokens.append(draft_token.unsqueeze(0))
            # add the chosen token to the input for the next step. 
            draft_model_input = torch.cat([draft_model_input, draft_token.unsqueeze(0)], dim=-1)

        print(f"draft proposed: {tokenizer.decode([t.item() for t in draft_tokens])}")

        # after the K iters above, draft_model_input = prefix + K tokens
        p_probs = forward_pass(target_model, temperature, draft_model_input) # [prefix_len + K, vocab_size]

        # rejection sampling
        
        corrected = False
        vocab_len = p_probs.shape[1]
        num_accepted = 0
        for i in range(K):
            p_i_v_i = p_probs[-(K-i+1), draft_tokens[i].item()]
            acceptance_prob = min(1.0,  (p_i_v_i / q_i_v_i[i]).item())
            print(f"  token {i}: '{tokenizer.decode([draft_tokens[i].item()])}' p={p_i_v_i.item():.4f} q={q_i_v_i[i].item():.4f} acceptance={acceptance_prob:.4f}")

            sample = torch.rand(1).item()

            if sample <= acceptance_prob:
                print(f"full_seq shape: {full_seq.shape}")
                print(f"draft_tokens[i] shape: {draft_tokens[i].shape}")
                # accept the draft token
                full_seq = torch.cat([full_seq, draft_tokens[i]], dim=1)
                print("accepted token: ", draft_tokens[i])
                num_accepted += 1
            else:
                # sample the correction token
                corrected = True
                residual = torch.clamp(p_probs[-(K-i+1), :] - q_probs_full[i], min=0)
                residual = residual / residual.sum()
                corrected_token = torch.multinomial(residual, 1).unsqueeze(0)
                full_seq = torch.cat([full_seq, corrected_token], dim=1)
                print("corrected token: ", corrected_token)
                break

        if not corrected:
            # sample last token from p(x)
            last_token = torch.multinomial(p_probs[-1, :], 1).unsqueeze(0)
            full_seq = torch.cat([full_seq, last_token], dim=1)

        print(f"round {round_num}: accepted {num_accepted}/{K} draft tokens")
        print(f"full_seq after round {round_num}: '{tokenizer.decode(full_seq[0], skip_special_tokens=True)}'")

        round_num += 1

    return full_seq

# ------------------------------------------------------------------
# Baseline: standard autoregressive sampling from target only
# ------------------------------------------------------------------

def autoregressive_decode(
    model,
    input_ids: torch.Tensor,
    max_new_tokens: int,
    temperature: float = 1.0,
) -> torch.Tensor:
    """Standard one-token-at-a-time sampling. Baseline for comparison."""
    generated = input_ids.clone()
    with torch.no_grad():
        for _ in range(max_new_tokens):
            logits = model(generated).logits[0, -1, :]
            if temperature == 0:
                next_token = logits.argmax().unsqueeze(0).unsqueeze(0)
            else:
                probs = F.softmax(logits / temperature, dim=-1)
                next_token = torch.multinomial(probs, 1).unsqueeze(0)
            generated = torch.cat([generated, next_token], dim=1)
    return generated


# ------------------------------------------------------------------
# Metrics
# ------------------------------------------------------------------

def run_comparison(args, tokenizer, draft, target, device):
    input_ids = tokenizer.encode(args.prompt, return_tensors="pt").to(device)

    print(f"\nPrompt: {args.prompt}")
    print(f"K={args.K}, max_new_tokens={args.max_new_tokens}\n")

    # --- speculative ---
    t0 = time.monotonic()
    spec_output = speculative_decode(
        draft, target, tokenizer, input_ids,
        K=args.K,
        max_new_tokens=args.max_new_tokens,
        temperature=args.temperature,
        device=device,
    )
    spec_time = time.monotonic() - t0

    # --- autoregressive baseline (target only) ---
    t0 = time.monotonic()
    ar_output = autoregressive_decode(
        target, input_ids,
        max_new_tokens=args.max_new_tokens,
        temperature=args.temperature,
    )
    ar_time = time.monotonic() - t0

    print("=== Speculative ===")
    print(tokenizer.decode(spec_output[0], skip_special_tokens=True))
    print(f"Time: {spec_time:.2f}s")

    print("\n=== Autoregressive (target only) ===")
    print(tokenizer.decode(ar_output[0], skip_special_tokens=True))
    print(f"Time: {ar_time:.2f}s")

    print(f"\nSpeedup: {ar_time / spec_time:.2f}x")


# ------------------------------------------------------------------
# Entry point
# ------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--prompt", type=str, default="The meaning of life is")
    parser.add_argument("--K", type=int, default=4,
                        help="Number of draft tokens per round")
    parser.add_argument("--max-new-tokens", type=int, default=100)
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--draft-model", type=str, default="gpt2")
    parser.add_argument("--target-model", type=str, default="gpt2-xl")
    parser.add_argument("--device", type=str, default="mps")
    args = parser.parse_args()

    tokenizer, draft, target = load_models(
        args.draft_model, args.target_model, args.device
    )

    run_comparison(args, tokenizer, draft, target, args.device)